"""
Email digest generator for News Agent
Sends daily or weekly summaries to subscribers
"""
import json
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timezone
import sqlite3

def load_subscribers():
    """Load email subscribers from file"""
    if os.path.exists("subscribers.json"):
        with open("subscribers.json") as f:
            return json.load(f)
    return {"emails": []}

def save_subscribers(subscribers):
    """Save subscribers to file"""
    with open("subscribers.json", "w") as f:
        json.dump(subscribers, f, indent=2)

def get_top_articles(limit=10):
    """Get top articles from today"""
    try:
        with open("news.json") as f:
            data = json.load(f)
            items = sorted(
                data.get("items", []),
                key=lambda x: (x.get("impact", "").count("🔴"), x.get("published", "")),
                reverse=True
            )
            return items[:limit]
    except:
        return []

def generate_html_digest(articles, digest_type="daily"):
    """Generate HTML email digest"""
    high_impact = [a for a in articles if "🔴" in a.get("impact", "")]
    
    html = f"""
    <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; color: #333; }}
                .header {{ background: linear-gradient(135deg, #3b82f6 0%, #10b981 100%); 
                           color: white; padding: 20px; text-align: center; }}
                .article {{ border-left: 4px solid #3b82f6; padding: 15px; margin: 10px 0; 
                           background: #f9fafb; }}
                .impact {{ font-weight: bold; font-size: 1.2em; }}
                .badge {{ display: inline-block; padding: 5px 10px; 
                         background: #dbeafe; color: #1e40af; border-radius: 3px; 
                         margin: 5px 5px 5px 0; font-size: 0.85em; }}
                .footer {{ text-align: center; color: #999; padding: 20px; 
                          border-top: 1px solid #e5e7eb; margin-top: 20px; }}
                a {{ color: #3b82f6; text-decoration: none; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📰 News Agent - {digest_type.title()} Digest</h1>
                <p>Your AI-curated news summary</p>
            </div>
            
            <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2>🔴 High Impact Stories ({len(high_impact)})</h2>
                {"".join([f'''
                    <div class="article">
                        <div class="impact">{a.get("impact", "")} {a.get("title", "")}</div>
                        <p style="color: #666; margin: 10px 0;">{a.get("summary_short", a.get("summary", "")[:200])}</p>
                        <div>
                            <span class="badge">{a.get("sector", "")}</span>
                            <span class="badge">{a.get("source", "")}</span>
                        </div>
                        <p style="margin-top: 10px;"><strong>Why:</strong> {a.get("why", "")}</p>
                        <p><strong>Effect:</strong> {a.get("effect", "")}</p>
                        <a href="{a.get("link", "#")}">Read Full Article →</a>
                    </div>
                ''' for a in high_impact[:5]])}
                
                <h2>📰 Other Top Stories</h2>
                {"".join([f'''
                    <div class="article">
                        <div class="impact">{a.get("impact", "")} {a.get("title", "")}</div>
                        <div>
                            <span class="badge">{a.get("sector", "")}</span>
                            <span class="badge">{a.get("source", "")}</span>
                        </div>
                        <a href="{a.get("link", "#")}">Read →</a>
                    </div>
                ''' for a in articles[5:10]])}
                
                <div class="footer">
                    <p>📊 <a href="https://<username>.github.io/news-agent/">View Full Dashboard</a></p>
                    <p>🔔 <a href="mailto:?subject=Unsubscribe from News Agent">Manage Subscription</a></p>
                    <p style="font-size: 0.85em;">Generated by News Agent • {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</p>
                </div>
            </div>
        </body>
    </html>
    """
    return html

def send_digest(smtp_server, smtp_port, sender_email, sender_password, recipients, digest_html, digest_type="daily"):
    """Send email digest"""
    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)
        
        for recipient in recipients:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"📰 News Agent - {digest_type.title()} Digest"
            msg["From"] = sender_email
            msg["To"] = recipient
            
            msg.attach(MIMEText(digest_html, "html"))
            server.sendmail(sender_email, recipient, msg.as_string())
            print(f"✓ Digest sent to {recipient}")
        
        server.quit()
        return True
    except Exception as e:
        print(f"Email error: {e}")
        return False

def generate_text_digest(articles, digest_type="daily"):
    """Generate plain text digest"""
    text = f"📰 NEWS AGENT - {digest_type.upper()} DIGEST\n"
    text += "=" * 50 + "\n\n"
    
    for i, article in enumerate(articles[:10], 1):
        text += f"{i}. {article.get('impact', '')} {article.get('title', '')}\n"
        text += f"   Sector: {article.get('sector', '')}\n"
        text += f"   Source: {article.get('source', '')}\n"
        text += f"   Why: {article.get('why', '')}\n"
        text += f"   Link: {article.get('link', '#')}\n\n"
    
    text += "=" * 50 + "\n"
    text += f"View full dashboard at: https://<username>.github.io/news-agent/\n"
    text += f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
    
    return text

if __name__ == "__main__":
    # Example usage (configure with your email settings)
    subscribers = load_subscribers()
    articles = get_top_articles(10)
    
    if articles and subscribers.get("emails"):
        html = generate_html_digest(articles, "daily")
        print(generate_text_digest(articles, "daily"))
        
        # Uncomment to send emails:
        # send_digest(
        #     smtp_server="smtp.gmail.com",
        #     smtp_port=587,
        #     sender_email="your-email@gmail.com",
        #     sender_password="your-app-password",
        #     recipients=subscribers["emails"],
        #     digest_html=html,
        #     digest_type="daily"
        # )
