      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "news-bot"
          git add .
          git diff-index --quiet HEAD || {
            git commit -m "news update $(date -u)"
            git pull --rebase origin main
            git push origin main
          }
